/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author LEONEL
 */
public class RegistoProcesso extends javax.swing.JPanel {

    /**
     * Creates new form RegistoProcesso
     */
    public RegistoProcesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(961, 530));
        setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("MOVIMENTO PROCESSUAL");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 47, 337, 33);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 960, 90);

        jPanel3.setMinimumSize(new java.awt.Dimension(460, 380));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("REGISTO INICIAL");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(144, 11, 163, 24);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Numero do Processo:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 60, 159, 24);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("Natureza:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(110, 110, 72, 24);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setText("Data de Entrada:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(60, 160, 125, 24);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setText("Nome do denunciante:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 210, 164, 24);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel7.setText("Nome do arguido:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 260, 132, 24);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(190, 60, 262, 30);

        jComboBox1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Querela" }));
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(190, 110, 262, 32);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(190, 160, 262, 30);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(190, 200, 262, 32);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(190, 250, 262, 31);

        jButton1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jButton1.setText("Cadastrar");
        jPanel3.add(jButton1);
        jButton1.setBounds(100, 330, 104, 35);

        jButton2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jButton2.setText("Limpar");
        jPanel3.add(jButton2);
        jButton2.setBounds(220, 330, 94, 37);

        jButton3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jButton3.setText("Sair");
        jPanel3.add(jButton3);
        jButton3.setBounds(340, 330, 105, 37);

        jPanel4.setMinimumSize(new java.awt.Dimension(480, 330));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setText("REGISTOS SUBSEQUENTES");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(125, 11, 256, 24);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setText("Data do julgamento:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(19, 66, 149, 24);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(172, 63, 272, 30);

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setText("Decisao:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(106, 115, 62, 24);

        jComboBox2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Absolvido", "Condenado" }));
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(172, 111, 272, 32);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel11.setText("Interposicao de Recurso:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 169, 182, 24);

        jComboBox3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Nao" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(196, 161, 248, 32);

        jButton4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jButton4.setText("Actualizar");
        jPanel4.add(jButton4);
        jButton4.setBounds(174, 245, 99, 38);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );

        add(jPanel2);
        jPanel2.setBounds(0, 102, 970, 410);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
